export const moduleActionTypes = {
  FETCH_MODULES_START: 'FETCH_MODULES_START',
  FETCH_MODULES_SUCCESS: 'FETCH_MODULES_SUCCESS',
  FETCH_MODULES_FAILURE: 'FETCH_MODULES_FAILURE',
  ADD_MODULE_START: 'ADD_MODULE_START',
  ADD_MODULE_SUCCESS: 'ADD_MODULE_SUCCESS',
  ADD_MODULE_FAILURE: 'ADD_MODULE_FAILURE'
};
